version: "1.0"
info:
  model: int-scaffold
packages:
- name: DocTypeTestProject
  gitServerName: SanthoshKUserSanthosh
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.doctypetest.integrations:Test3
  packages:
  - name: DocTypeTestProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.1957
